name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  action:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
      - run: dotnet restore Mad.slnx && dotnet tool restore
      - run: dotnet csharpier check .
      - run: dotnet build Mad.slnx --no-restore --configuration Release
